# Generated by Django 5.0.1 on 2025-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0002_alter_outbounddelivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='direccion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
