# Generated by Django 5.0.1 on 2025-01-24 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0003_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbounddelivery',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_deliveries', to='outbound.place'),
        ),
        migrations.AlterField(
            model_name='outbounddelivery',
            name='destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
