# Generated by Django 5.0.1 on 2025-01-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0004_outbounddelivery_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud de la ubicación.', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude de la ubicación.', max_digits=9, null=True),
        ),
    ]
