# Generated by Django 5.0.1 on 2025-02-01 23:53
import got.paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import got.models
from decimal import Decimal

class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('firma', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('dpto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='got_userprofile',
        ),
        migrations.CreateModel(
            name='OvertimeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.asset')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('nombre_completo', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cedula', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, choices=[('a', 'Capitán'), ('b', 'Primer Oficial de Puente'), ('c', 'Marino'), ('d', 'Jefe de Máquinas'), ('e', 'Primer Oficial de Máquinas'), ('f', 'Maquinista'), ('g', 'Otro')], max_length=1, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dth.overtimeproject')),
                ('state', models.CharField(choices=[('a', 'Aprobado'), ('b', 'No aprobado'), ('c', 'Pendiente')], default='c', max_length=1)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dth.nomina')),
            ],
            options={
                'db_table': 'got_overtime',
                'permissions': [('can_approve_overtime', 'Puede aprobar horas extras')],
            },
        ),
        migrations.CreateModel(
            name='NominaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes (1-12).')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año.')),
                ('dv01', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sueldo básico (código dv01).', max_digits=18)),
                ('dv25', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pago Vacaciones (código dv25).', max_digits=18)),
                ('dv03', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subsidio de transporte (código dv03).', max_digits=18)),
                ('dv103', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Licencia de la familia', max_digits=18)),
                ('dv27', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Intereses de cesantías año anterior.', max_digits=18)),
                ('dv30', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cesantías.', max_digits=18)),
                ('dx03', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pensión.', max_digits=18)),
                ('dx05', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solidaridad.', max_digits=18)),
                ('dx01', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención en la fuente.', max_digits=18)),
                ('dx07', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exequias Lordoy.', max_digits=18)),
                ('dx12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento pensión voluntaria.', max_digits=18)),
                ('dx63', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Banco de Occidente.', max_digits=18)),
                ('dx64', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confenalco.', max_digits=18)),
                ('dx66', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Préstamo empleado.', max_digits=18)),
                ('nomina', models.ForeignKey(help_text='Empleado asociado a este registro de nómina.', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='dth.nomina')),
            ],
        ),
    ]
