# Generated by Django 5.0.1 on 2025-02-01 23:53
import got.paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import got.models

class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('firma', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('dpto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='got_userprofile',
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('justificacion', models.TextField()),
                ('nombre_completo', models.CharField(default='', max_length=200)),
                ('cedula', models.CharField(default='', max_length=20)),
                ('cargo', models.CharField(choices=[('a', 'Capitán'), ('b', 'Primer Oficial de Puente'), ('c', 'Marino'), ('d', 'Jefe de Máquinas'), ('e', 'Primer Oficial de Máquinas'), ('f', 'Maquinista'), ('g', 'Otro')], max_length=1)),
                ('approved', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='got.asset')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'got_overtime',
                'permissions': [('can_approve_overtime', 'Puede aprobar horas extras')],
            },
        ),
    ]
