# Generated by Django 5.0.1 on 2025-03-18 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del departamento.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(help_text='Identificación del empleado (no es pk).', max_length=50, verbose_name='Número de documento')),
                ('name', models.CharField(help_text='Nombre del empleado.', max_length=100)),
                ('surname', models.CharField(help_text='Apellido del empleado.', max_length=100)),
                ('position', models.CharField(help_text='Cargo o puesto.', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salario en pesos colombianos.', max_digits=12)),
                ('category', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Operativo', 'Operativo'), ('Mixto', 'Mixto')], default='Operativo', help_text='Categoria del empleado.', max_length=15)),
                ('dpto', models.ForeignKey(help_text='Departamento al que pertenece el empleado.', on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='dth.department')),
            ],
        ),
    ]
