# Generated by Django 5.0.1 on 2025-03-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='position',
        ),
        migrations.AlterField(
            model_name='nomina',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dth.position'),
        ),
    ]
