# Generated by Django 5.0.1 on 2025-03-18 21:37

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del departamento.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(help_text='Identificación del empleado.', max_length=50, verbose_name='Número de documento')),
                ('name', models.CharField(help_text='Nombre del empleado.', max_length=100)),
                ('surname', models.CharField(help_text='Apellido del empleado.', max_length=100)),
                ('position', models.CharField(help_text='Cargo o puesto.', max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, help_text='Salario en COP.', max_digits=18)),
                ('admission', models.DateField(help_text='Fecha de ingreso del empleado. (Obligatoria)')),
                ('expiration', models.DateField(blank=True, help_text='Fecha de expiración del contrato, si aplica.', null=True)),
                ('risk_class', models.CharField(blank=True, choices=[('I', '0.522%'), ('II', '1.044%'), ('III', '2.436%'), ('IV', '4.350%'), ('V', '6.96%')], help_text='Clase de riesgo laboral.', max_length=3, null=True)), 
                ('is_driver', models.BooleanField(default=False)), 
            ],
        ),
    ]


    # dependencies = [
    #     ('dth', '0003_nominareport_current_salary_alter_nomina_admission_and_more'),
    #     ('got', '0005_alter_equipo_date_inv_alter_equipo_estado_and_more'),
    #     migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    # ]