# Generated by Django 5.0.1 on 2025-02-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='station',
            new_name='dpto',
        ),

    ]
