# Generated by Django 5.0.1 on 2025-03-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0002_remove_nomina_position_alter_nomina_position_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dpto',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payroll_view_mode',
            field=models.CharField(choices=[('c', 'Tarjetas'), ('t', 'Tabla')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='overtimeproject',
            name='ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ot'),
        ),
    ]
