# Generated by Django 5.0.1 on 2025-03-20 23:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0002_department_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominareport',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salario Actual', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='admission',
            field=models.DateField(help_text='Fecha de ingreso del empleado. (Obligatoria)'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='risk_class',
            field=models.CharField(blank=True, choices=[('I', '0.522%'), ('II', '1.044%'), ('III', '2.436%'), ('IV', '4.350%'), ('V', '6.96%')], help_text='Clase de riesgo laboral.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv01',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sueldo básico.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv03',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subsidio de transporte', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv25',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pago Vacaciones', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='dth.nomina'),
        ),
    ]
