# Generated by Django 5.0.1 on 2025-03-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0002_department_nomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='dpto',
        ),
    ]
