# Generated by Django 5.0.1 on 2025-03-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0002_department_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='dth.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.CharField(blank=True, choices=[('o', 'Operativo'), ('a', 'Administrativo'), ('m', 'Mixto')], max_length=1, null=True),
        ),
    ]
