# Generated by Django 5.0.1 on 2025-03-18 23:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_remove_nomina_dpto'),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes (1-12).')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año.')),
                ('dv01', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sueldo básico (código dv01).', max_digits=12)),
                ('dv25', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pago Vacaciones (código dv25).', max_digits=12)),
                ('dv03', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subsidio de transporte (código dv03).', max_digits=12)),
                ('dv103', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Licencia de la familia (código dv103).', max_digits=12)),
                ('dv27', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Intereses de cesantías año anterior (código dv27).', max_digits=12)),
                ('dv30', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cesantías (código dv30).', max_digits=12)),
                ('dx03', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pensión (código dx03).', max_digits=12)),
                ('dx05', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solidaridad (código dx05).', max_digits=12)),
                ('dx01', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención en la fuente (código dx01).', max_digits=12)),
                ('dx07', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exequias Lordoy (código dx07).', max_digits=12)),
                ('dx12', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento pensión voluntaria (código dx12).', max_digits=12)),
                ('dx63', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Banco de Occidente (código dx63).', max_digits=12)),
                ('dx64', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confenalco (código dx64).', max_digits=12)),
                ('dx66', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Préstamo empleado (código dx66).', max_digits=12)),
                ('nomina', models.ForeignKey(help_text='Empleado asociado a este registro de nómina.', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='dth.nomina')),
            ],
        ),
    ]
