# Generated by Django 5.0.1 on 2025-03-22 17:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_nominareport_current_salary_alter_nomina_admission_and_more'),
        ('got', '0005_alter_equipo_date_inv_alter_equipo_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomina',
            old_name='doc_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='overtime',
            old_name='hora_inicio',
            new_name='start',
        ),
        migrations.AddField(
            model_name='overtime',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dth.nomina'),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv103',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Licencia de la familia', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv27',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Intereses de cesantías año anterior.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv30',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cesantías.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx01',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención en la fuente.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx03',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pensión.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx05',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solidaridad.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx07',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exequias Lordoy.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx12',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento pensión voluntaria.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx63',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Banco de Occidente.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx64',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confenalco.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx66',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Préstamo empleado.', max_digits=18),
        ),
        migrations.CreateModel(
            name='OvertimeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.asset')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
