# Generated by Django 5.0.1 on 2025-03-31 06:41

import dth.models.positions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_remove_userprofile_dpto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=dth.models.positions.get_upload_path_employee),
        ),
    ]
