# Generated by Django 5.0.1 on 2025-04-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_remove_userprofile_dpto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del empleado.', max_length=254, null=True),
        ),
    ]
