# Generated by Django 5.0.1 on 2025-04-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_remove_userprofile_dpto_and_more'),
        ('got', '0005_alter_asset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeproject',
            name='ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ot'),
        ),
    ]
