# Generated by Django 5.0.1 on 2025-03-28 09:36

import got.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_document_position_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='gender',
            field=models.CharField(choices=[('h', 'Hombre'), ('m', 'Mujer')], default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='nomina',
            name='photo',
            field=models.ImageField(blank=True, help_text='Fotografía del empleado.', null=True, upload_to=got.paths.get_upload_path),
        ),
    ]
