# Generated by Django 5.0.1 on 2025-04-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_remove_userprofile_dpto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='risk_class',
        ),
        migrations.RemoveField(
            model_name='nomina',
            name='salary',
        ),
    ]
