# Generated by Django 5.0.1 on 2025-03-19 23:04

import dth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_remove_nomina_dpto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomina',
            name='category',
        ),
        migrations.AddField(
            model_name='nomina',
            name='admission',
            field=models.DateField(default=dth.models.get_default_admission, help_text='Fecha de ingreso del empleado. (Obligatoria)'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='expiration',
            field=models.DateField(blank=True, help_text='Fecha de expiración del contrato, si aplica.', null=True),
        ),
        migrations.AddField(
            model_name='nomina',
            name='risk_class',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], help_text='Clase de riesgo laboral.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='doc_number',
            field=models.CharField(help_text='Identificación del empleado.', max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Salario en COP.', max_digits=18),
        ),
    ]
