# Generated by Django 5.0.1 on 2025-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0003_nominareport_current_salary_alter_nomina_admission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='reportado_por',
        ),
        migrations.AddField(
            model_name='nomina',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
