# Generated by Django 5.0.1 on 2025-03-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0004_rename_doc_number_nomina_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeproject',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
