# Generated by Django 5.0.1 on 2025-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0004_overtimeproject_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
