# Generated by Django 5.0.1 on 2025-03-18 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0004_nominareport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominareport',
            name='dv01',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sueldo básico (código dv01).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv03',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subsidio de transporte (código dv03).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv103',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Licencia de la familia (código dv103).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv25',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pago Vacaciones (código dv25).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv27',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Intereses de cesantías año anterior (código dv27).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dv30',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cesantías (código dv30).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx01',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retención en la fuente (código dx01).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx03',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pensión (código dx03).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx05',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solidaridad (código dx05).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx07',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Exequias Lordoy (código dx07).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx12',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento pensión voluntaria (código dx12).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx63',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Banco de Occidente (código dx63).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx64',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confenalco (código dx64).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='nominareport',
            name='dx66',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Préstamo empleado (código dx66).', max_digits=18),
        ),
    ]
