# Generated by Django 5.0.1 on 2025-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0004_nomina_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequestitem',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequestitem',
            name='status',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
    ]
