# Generated by Django 5.0.1 on 2025-03-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0004_rename_doc_number_nomina_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='asset',
        ),
        migrations.AlterField(
            model_name='overtime',
            name='cargo',
            field=models.CharField(blank=True, choices=[('a', 'Capitán'), ('b', 'Primer Oficial de Puente'), ('c', 'Marino'), ('d', 'Jefe de Máquinas'), ('e', 'Primer Oficial de Máquinas'), ('f', 'Maquinista'), ('g', 'Otro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='nombre_completo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
