# Generated by Django 5.0.1 on 2025-04-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0004_remove_nomina_admission_remove_nomina_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolldetails',
            name='profession',
            field=models.CharField(blank=True, help_text='Profesión del empleado.', max_length=200, null=True),
        ),
    ]
