# Generated by Django 5.0.1 on 2025-03-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dth', '0005_overtimeproject_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dth.overtimeproject'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='state',
            field=models.CharField(choices=[('a', 'Aprobado'), ('b', 'No aprobado'), ('c', 'Pendiente')], default='c', max_length=1),
        ),
    ]
