# Generated by Django 5.0.1 on 2025-01-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_darbaja_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darbaja',
            options={'ordering': ['-fecha']},
        ),
    ]
