# Generated by Django 5.0.1 on 2025-04-09 10:19

import django.db.models.deletion
import got.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_darbaja_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiredSupplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=got.paths.get_upload_path)),
                ('creation', models.DateField(auto_now_add=True)),
                ('retired_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inv.retiredsupply')),
            ],
        ),
    ]
