# Generated by Django 5.0.1 on 2025-01-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_darbaja_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darbaja',
            options={'ordering': ['-fecha']},
        ),
        migrations.RunSQL(
            """
            UPDATE django_content_type
            SET app_label = 'inv'
            WHERE app_label = 'got' AND model = 'transferencia';
            """,
            reverse_sql="""
            UPDATE django_content_type
            SET app_label = 'got'
            WHERE app_label = 'inv' AND model = 'transferencia';
            """
        ),
    ]
