# Generated by Django 5.0.1 on 2025-03-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_alter_asset_options'),
        ('inv', '0002_alter_darbaja_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transferencia',
            new_name='Transference',
        ),
        migrations.AlterModelTable(
            name='transference',
            table=None,
        ),
    ]
