# Generated by Django 5.0.1 on 2025-04-07 01:05

import django.core.validators
import got.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_darbaja_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('can_add_supply', 'Puede añadir suministros'), ('can_edit_only_today', 'Puede modificar transacciones SOLO en la fecha actual'))},
        ),
        migrations.AddField(
            model_name='transaction',
            name='remision',
            field=models.FileField(blank=True, help_text='PDF/Imagen con la remisión del ingreso', null=True, upload_to=got.paths.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
