# Generated by Django 5.0.1 on 2025-02-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_darbaja_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
