# Generated by Django 5.0.1 on 2025-01-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_darbaja_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbaja',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
