# Generated by Django 5.0.1 on 2025-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_darbaja_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='receptor',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
