# Generated by Django 5.0.1 on 2025-03-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_rename_transferencia_transference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transference',
            name='signature',
            field=models.ImageField(default='', help_text='Firma obligatoria en formato de imagen (jpg, png, etc.)', upload_to='transference_signatures/'),
            preserve_default=False,
        ),
    ]
