# Generated by Django 5.0.1 on 2025-04-09 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_retiredsupply_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retiredsupply',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='retired_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='inv.retiredsupply'),
        ),
    ]
