# Generated by Django 5.0.1 on 2025-01-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_darbaja_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_abbreviation', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Código de Equipo',
                'verbose_name_plural': 'Contadores de Códigos de Equipo',
                'unique_together': {('asset_abbreviation', 'tipo')},
            },
        ),
    ]
