# Generated by Django 5.0.1 on 2025-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_transferencia_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbaja',
            name='motivo',
            field=models.CharField(choices=[('o', 'Obsoleto'), ('r', 'Robo/Hurto'), ('p', 'Perdida'), ('i', 'Inservible/depreciado'), ('v', 'Venta')], max_length=1),
        ),
    ]
