# Generated by Django 5.0.1 on 2025-01-30 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_equipocodecounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipoCodeCounter',
        ),
    ]
