# Generated by Django 5.0.1 on 2025-01-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_delete_equipocodecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_abbr', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=2)),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Código de Equipo',
                'verbose_name_plural': 'Contadores de Código de Equipo',
                'unique_together': {('asset_abbr', 'tipo')},
            },
        ),
    ]
