# Generated by Django 5.0.1 on 2025-02-17 00:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_alter_darbaja_motivo'),
    ]

    operations = [
       migrations.RunSQL(
            """
            UPDATE django_content_type
            SET app_label = 'inv'
            WHERE app_label = 'got' AND model = 'got';
            """,
            reverse_sql="""
            UPDATE django_content_type
            SET app_label = 'got'
            WHERE app_label = 'inv' AND model = 'inv';
            """
        ),
    ]
