# Generated by Django 5.0.1 on 2025-02-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_transaction_transaction_unique_suministro_fecha_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='responsable',
            field=models.CharField(max_length=150),
        ),
    ]
