# Generated by Django 5.0.1 on 2025-02-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_alter_transferencia_responsable'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transferencia',
            table=None,
        ),
    ]
