# Generated by Django 5.0.1 on 2025-02-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='got_transaction',
        ),
    ]
