# Generated by Django 5.0.1 on 2024-03-08 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import got.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('presentacion', models.CharField(max_length=10)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('seccion', models.CharField(choices=[('c', 'Consumibles'), ('h', 'Herramientas y Elementos'), ('r', 'Repuestos')], default='c', max_length=1)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={'ordering': ['name', 'reference']},
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('abbreviation', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('a', 'Motonave'), ('b', 'Buceo'), ('c', 'Barcazas'), ('o', 'Oceanografía'), ('l', 'Locativo'), ('v', 'Vehiculos'), ('x', 'Apoyo')], default='a', max_length=1)),
                ('bandera', models.CharField(blank=True, default='Colombia', max_length=50, null=True)),
                ('eslora', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('manga', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('puntal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('calado_maximo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('deadweight', models.IntegerField(blank=True, default=0, null=True)),
                ('arqueo_bruto', models.IntegerField(blank=True, default=0, null=True)),
                ('arqueo_neto', models.IntegerField(blank=True, default=0, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('capitan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Capitanes', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_assets', to=settings.AUTH_USER_MODEL)),
                ('show', models.BooleanField(default=True)),
                ('maintenance_compliance_cache', models.DecimalField(blank=True, decimal_places=2, help_text='Valor cacheado de mantenimiento (%)', max_digits=5, null=True)),
            ],
            options={
                'ordering': ['area', 'name'],
                'permissions': (('can_see_completely', 'Access to completely info'),),
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, default='Cartagena', max_length=50, null=True)),
                ('state', models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operativo'), ('x', 'Fuera de servicio'), ('s', 'Stand by')], default='m', max_length=1)),
                ('asset', models.ForeignKey(to='got.asset', on_delete=models.CASCADE)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('creation_date', models.DateField(auto_now_add=True)),
                ('num_ot', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('a', 'Abierto'), ('x', 'En ejecución'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='x', max_length=1)),
                ('tipo_mtto', models.CharField(choices=[('p', 'Preventivo'), ('c', 'Correctivo'), ('m', 'Modificativo')], max_length=1)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.system')),
                ('sign_supervision', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_ots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-num_ot'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date_inv', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('feature', models.TextField()),
                ('horometro', models.IntegerField(blank=True, default=0, null=True)),
                ('initial_hours', models.IntegerField(default=0)),
                ('prom_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('manual_pdf', models.FileField(blank=True, null=True, upload_to=got.models.get_upload_pdfs)),
                ('tipo_almacenamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('volumen', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='got.system')),
                ('tipo', models.CharField(choices=[('a', 'Climatización'), ('b', 'Bomba'), ('c', 'Compresor'), ('d', 'Grúa'), ('e', 'Motor eléctrico'), ('f', 'Emergencias'), ('g', 'Generador'), ('h', 'Cilindro hidráulico'), ('i', 'Instrumentos y herramientas'), ('j', 'Distribución eléctrica'), ('k', 'Tanque de almacenamiento'), ('l', 'Gobierno'), ('m', 'Comunicación'), ('n', 'Navegación'), ('o', 'Maniobras'), ('p', 'Habitabilidad'), ('q', 'Informatica y vigilacia'), ('nr', 'No rotativo'), ('r', 'Motor a combustión'), ('t', 'Transmisión'), ('u', 'Unidad Hidráulica'), ('v', 'Valvula'), ('w', 'Winche'), ('x', 'Estructuras'), ('y', 'Soporte de vida'), ('z', 'Banco de baterias')], default='nr', max_length=2)),
                ('subsystem', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('critico', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_with', to='got.equipo')),
                ('qr_code_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hse', models.TextField(blank=True, default='', null=True)),
                ('procedimiento', models.TextField(blank=True, default='', null=True)),
                ('news', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('men_time', models.IntegerField(default=0)),
                ('finished', models.BooleanField()),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ot')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.IntegerField(blank=True, default=0, null=True)),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ruta')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_tasks', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
            ],
            options={
                'ordering': ['-priority', '-start_date'],
                'permissions': (
                    ('can_reschedule_task', 'Reprogramar actividades'),
                    ('can_modify_any_task', 'Can modify any task')
                    ),
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('frecuency', models.IntegerField()),
                ('intervention_date', models.DateField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='got.system')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='got.ot')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='got.equipo')),
                ('control', models.CharField(choices=[('d', 'Días'), ('h', 'Horas'), ('k', 'Kilómetros')], max_length=1)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependiente', to='got.ruta')),
                ('nivel', models.IntegerField(choices=[(1, 'Nivel 1 - Operadores'), (2, 'Nivel 2 - Técnico'), (3, 'Nivel 3 - Proveedor especializado'), (4, 'Nivel 4 - Fabricante')], default=1)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('clase_date', models.DateField(blank=True, help_text='(Opcional) Fecha en que se renovó el certificado de clase, si es un dique de clase.', null=True)),
            ],
            options={'ordering': ['frecuency']},
        ),
        
    ]
