# Generated by Django 5.0.1 on 2024-03-08 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import got.models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True)),
                ('critico', models.BooleanField()),
                ('description', models.TextField()),
                ('causas', models.TextField()),
                ('suggest_repair', models.TextField(blank=True, null=True)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_report', to='got.ot')),
                ('closed', models.BooleanField(default=False)),
                ('impact', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('s', 'La seguridad personal'), ('m', 'El medio ambiente'), ('i', 'Integridad del equipo/sistema'), ('o', 'El desarrollo normal de las operaciones')], max_length=1), blank=True, default=list, size=None)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_failures', to=settings.AUTH_USER_MODEL)),
                ('report', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={'ordering': ['-moment']},
        ),
        migrations.CreateModel(
            name='HistoryHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='got.equipo')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('proyecto', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.asset')),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.operation')),
                ('novedad', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'permissions': [
                    ('can_create_requirement', 'Can create requirement'),
                    ('can_delete_requirement', 'Can delete requirement')
                ]
            }
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('suministros', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.asset')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ot')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('num_sc', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('sc_change_date', models.DateTimeField(blank=True, null=True)),
                ('cancel', models.BooleanField(default=False)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('cancel_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='Jader Aguilar', max_length=100, null=True)),
                ('recibido_por', models.TextField(blank=True, null=True)),
                ('satisfaccion', models.BooleanField(default=False)),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-creation_date'],
                'permissions': (
                    ('can_approve', 'Aprobar solicitudes'),
                    ('can_cancel', 'Puede cancelar'),
                ),
            },
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('Solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.solicitud')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.item')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suministros', to='got.equipo'),),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suministros', to='got.asset')),
            ],
        ),

        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=got.models.get_upload_path)),
                ('failure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.failurereport')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.task')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.solicitud')),
                ('darbaja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory_management.darbaja')),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outbound.outbounddelivery')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.equipo')),
                ('requirements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.requirement')),
                ('preoperacionaldiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preoperacionales.preoperacionaldiario')),
                ('preoperacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preoperacionales.preoperacional')),
            ],
        ),

        migrations.CreateModel(
            name='DarBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('reporter', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('activo', models.CharField(max_length=150)),
                ('motivo', models.CharField(choices=[('o', 'Obsoleto'), ('r', 'Robo/Hurto'), ('p', 'Perdida'), ('i', 'Inservible/depreciado')], max_length=1)),
                ('observaciones', models.TextField()),
                ('disposicion', models.TextField()),
                ('firma_responsable', models.ImageField(upload_to=got.models.get_upload_path)),
                ('firma_autorizado', models.ImageField(upload_to=got.models.get_upload_path),),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),

        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='got.system')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='got.system')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('recibe', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100, null=True)),
                ('auth', models.BooleanField(default=False)),
                ('responsable', models.CharField(max_length=100)),
                ('propietario', models.CharField(max_length=100)),
                ('sign_recibe', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('adicional', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
                'permissions': (('can_approve_it', 'Aprobar salidas'),),
            },
        ),

        # migrations.CreateModel(
        #     name='Megger',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('date_report', models.DateField(auto_now_add=True, null=True)),
        #         ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
        #         ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.ot')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Excitatriz',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('test_type', models.CharField(choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')], default='i', max_length=1)),
        #         ('pi_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_obs_l_tierra', models.TextField(blank=True, null=True)),
        #         ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Estator',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('test_type', models.CharField(choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')], default='i', max_length=1)),
        #         ('time_type', models.CharField(choices=[('1', '1 min'), ('2', '10 min')], default='1', max_length=1)),
        #         ('pi_1min_l1_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_1min_l2_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_1min_l3_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_1min_l1_l2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_1min_l2_l3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_1min_l3_l1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_obs_l1_tierra', models.TextField(blank=True, null=True)),
        #         ('pi_obs_l2_tierra', models.TextField(blank=True, null=True)),
        #         ('pi_obs_l3_tierra', models.TextField(blank=True, null=True)),
        #         ('pi_obs_l1_l2', models.TextField(blank=True, null=True)),
        #         ('pi_obs_l2_l3', models.TextField(blank=True, null=True)),
        #         ('pi_obs_l3_l1', models.TextField(blank=True, null=True)),
        #         ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='RodamientosEscudos',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('test_type', models.CharField(choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')], default='i', max_length=1)),
        #         ('rodamientoas', models.TextField(blank=True, null=True)),
        #         ('rodamientobs', models.TextField(blank=True, null=True)),
        #         ('escudoas', models.TextField(blank=True, null=True)),
        #         ('escudobs', models.TextField(blank=True, null=True)),
        #         ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='RotorAux',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('test_type', models.CharField(choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')], default='i', max_length=1)),
        #         ('pi_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_obs_l_tierra', models.TextField(blank=True, null=True)),
        #         ('pf_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pf_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pf_obs_l_tierra', models.TextField(blank=True, null=True)),
        #         ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='RotorMain',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('test_type', models.CharField(choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')], default='i', max_length=1)),
        #         ('pi_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pi_obs_l_tierra', models.TextField(blank=True, null=True)),
        #         ('pf_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pf_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
        #         ('pf_obs_l_tierra', models.TextField(blank=True, null=True)),
        #         ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
        #     ],
        # ),
    ]
