# Generated by Django 5.0.1 on 2024-03-08 04:01
import taggit.managers
import django.db.models.deletion
import got.models
from django.conf import settings
from django.db import migrations, models
from decimal import Decimal

class Migration(migrations.Migration):

    dependencies = [
        ('got', '0002_ruta_task_ruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preoperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cedula', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('salida', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('tipo_ruta', models.CharField(choices=[('u', 'Urbana'), ('r', 'Rural'), ('m', 'Mixta (Urbana y Rural)')], max_length=1)),
                ('autorizado', models.CharField(choices=[('a', 'Alejandro Angel/ Deliana Lacayo/ Jenny Castillo - Dpto. abasteciiento y logistica'), ('b', 'Juan Pablo Llanos - Residente Santa Marta'), ('c', 'Jose Jurado/ Julieth Ximena - Residente Tumaco'), ('d', 'Issis Alvarez - Directora Administrativa'), ('e', 'Jennifer Padilla - Gerente administrativa'), ('f', 'German Locarno - Gerente de operaciones'), ('g', 'Alexander Davey - Gerente de mantenimiento'), ('h', 'Carlos Cortés - Subgerente'), ('i', 'Federico Payan - Gerente Financiero'), ('j', 'Diego Lievano - Jefe de buceo'), ('k', 'Klaus Bartel - Gerente General')], max_length=1)),
                ('kilometraje', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agua', models.BooleanField()),
                ('condiciones', models.BooleanField()),
                ('control', models.BooleanField()),
                ('dormido', models.BooleanField()),
                ('enfermo', models.BooleanField()),
                ('horas_trabajo', models.BooleanField()),
                ('medicamentos', models.BooleanField()),
                ('molestias', models.BooleanField()),
                ('radio_aire', models.BooleanField()),
                ('sueño', models.BooleanField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
                ('nombre_no_registrado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={'ordering': ['-fecha']},
        ),

        migrations.AlterUniqueTogether(
            name='historyhour',
            unique_together={('component', 'report_date')},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=got.models.get_upload_pdfs)),
                ('description', models.CharField(max_length=200)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.asset')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.ot')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.equipo')),
                ('creation', models.DateField(auto_now_add=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('c', 'Certificado'), ('f', 'Ficha técnica'), ('i', 'Informe'), ('m', 'Manual'), ('p', 'Plano'), ('o', 'Otro')], default='o', max_length=1)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fecha', models.DateField()),
                ('user', models.CharField(max_length=100)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('i', 'Ingreso'), ('c', 'Consumo'), ('t', 'Transferencia')], default='i', max_length=1)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='got.suministro')),
                ('cant_report', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
            ],
            options={
                'permissions': (('can_add_supply', 'Puede añadir suministros'),),
            },
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('suministro', 'fecha', 'tipo'), name='unique_suministro_fecha_tipo'),
        ),
        migrations.CreateModel(
            name='DailyFuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('com_estimado_motor', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumptions', to='got.equipo')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('equipo', 'fecha')},
            },
        ),
    ]
