# Generated by Django 5.0.1 on 2025-04-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0002_ruta_task_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='calado',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='deadweight',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='eslora',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='material',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='puntal',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type_navigation',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type_of_trade',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type_vessel',
        ),
        migrations.AlterModelTable(
            name='equipocodecounter',
            table='inv_equipocodecounter',
        ),
    ]
