# Generated by Django 5.0.1 on 2024-03-08 04:01

import django.db.models.deletion
import got.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0002_ruta_task_ruta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preoperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cedula', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('salida', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('tipo_ruta', models.CharField(choices=[('u', 'Urbana'), ('r', 'Rural'), ('m', 'Mixta (Urbana y Rural)')], max_length=1)),
                ('autorizado', models.CharField(choices=[('a', 'Alejandro Angel/ Deliana Lacayo/ Jenny Castillo - Dpto. abasteciiento y logistica'), ('b', 'Juan Pablo Llanos - Residente Santa Marta'), ('c', 'Jose Jurado/ Julieth Ximena - Residente Tumaco'), ('d', 'Issis Alvarez - Directora Administrativa'), ('e', 'Jennifer Padilla - Gerente administrativa'), ('f', 'German Locarno - Gerente de operaciones'), ('g', 'Alexander Davey - Gerente de mantenimiento'), ('h', 'Carlos Cortés - Subgerente'), ('i', 'Federico Payan - Gerente Financiero'), ('j', 'Diego Lievano - Jefe de buceo'), ('k', 'Klaus Bartel - Gerente General')], max_length=1)),
                ('kilometraje', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agua', models.BooleanField()),
                ('condiciones', models.BooleanField()),
                ('control', models.BooleanField()),
                ('dormido', models.BooleanField()),
                ('enfermo', models.BooleanField()),
                ('horas_trabajo', models.BooleanField()),
                ('medicamentos', models.BooleanField()),
                ('molestias', models.BooleanField()),
                ('radio_aire', models.BooleanField()),
                ('sueño', models.BooleanField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
                ('nombre_no_registrado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={'ordering': ['-fecha']},
        ),

        migrations.AlterUniqueTogether(
            name='historyhour',
            unique_together={('component', 'report_date')},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=got.models.get_upload_pdfs)),
                ('description', models.CharField(max_length=200)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.asset')),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.ot')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('com_estimado_motor', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumptions', to='got.equipo')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('equipo', 'fecha')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='transaccionsuministro',
            unique_together={('suministro', 'fecha')},
        ),
    ]
