# Generated by Django 5.0.1 on 2025-04-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_asset_anio_remove_asset_arqueo_bruto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vessels',
            new_name='Vessel',
        ),
        migrations.AlterModelTable(
            name='equipocodecounter',
            table=None,
        ),
    ]
