# Generated by Django 5.0.1 on 2025-02-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='creation',
            field=models.DateField(auto_now_add=True, default='2025-02-11'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='area',
            field=models.CharField(choices=[('a', 'Motonave'), ('c', 'Barcazas'), ('o', 'Oceanografía'), ('l', 'Locativo'), ('v', 'Vehiculos'), ('x', 'Apoyo')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Operadores'), (2, 'Nivel 2 - Técnico'), (3, 'Nivel 3 - Proveedor especializado')], default=1),
        ),
    ]
