# Generated by Django 5.0.1 on 2025-02-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('b', 'BUEN ESTADO'), ('m', 'MAL ESTADO'), ('f', 'FUERA DE SERVICIO')], default='b', max_length=1),
        ),
    ]
