# Generated by Django 5.0.1 on 2024-09-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaccionsuministro',
            unique_together={('suministro', 'fecha')},
        ),
    ]
