# Generated by Django 5.0.1 on 2025-01-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='date_inv',
            field=models.DateField(auto_now_add=True, default='2024-06-24'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='seccion',
            field=models.CharField(choices=[('c', 'Consumibles'), ('h', 'Herramientas y Elementos'), ('r', 'Repuestos')], default='c', max_length=1),
        ),
    ]
