# Generated by Django 5.0.1 on 2024-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
