# Generated by Django 5.0.1 on 2024-08-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='adicional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='approved_by',
            field=models.CharField(blank=True, default='Jader Aguilar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='seccion',
            field=models.CharField(choices=[('c', 'Consumibles'), ('h', 'Herramientas y equipos'), ('r', 'Repuestos')], default='c', max_length=1),
        ),
    ]
