# Generated by Django 5.0.1 on 2025-01-26 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
        ('outbound', '0003_place_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Ubicación asociada (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='outbound.place'),
        ),
    ]
