# Generated by Django 5.0.1 on 2025-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_asset_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
