# Generated by Django 5.0.1 on 2024-08-25 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_alter_equipo_volumen_alter_solicitud_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('recibe', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100, null=True)),
                ('auth', models.BooleanField(default=False)),
                ('responsable', models.CharField(max_length=100)),
                ('propietario', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-fecha'],
                'permissions': (('can_approve_it', 'Aprobar salidas'),),
            },
        ),
        migrations.AddField(
            model_name='suministro',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suministros', to='got.salida'),
        ),
    ]
