# Generated by Django 5.0.1 on 2024-08-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_alter_equipo_volumen_alter_solicitud_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='presupuesto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='inversion',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='proveedor',
        ),
    ]
