# Generated by Django 5.0.1 on 2024-08-24 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_alter_equipo_volumen_alter_solicitud_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='info_contratista_pdf',
        ),
        migrations.AddField(
            model_name='ot',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto (COP)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='inversion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inversión (COP)'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor'),
        ),
    ]
