# Generated by Django 5.0.1 on 2024-08-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_alter_equipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('r', 'Motor a combustión'), ('nr', 'No rotativo'), ('e', 'Motor eléctrico/Generador'), ('g', 'Generador'), ('b', 'Bomba'), ('z', 'Banco de baterias'), ('t', 'Tanque de almacenamiento'), ('g', 'Cilindro hidraulico'), ('v', 'Valvulas'), ('t', 'Transmisión'), ('c', 'Compresor'), ('aa', 'Climatización'), ('i', 'Instrumentos y herramientas'), ('sn', 'Navegación'), ('sc', 'Comunicación'), ('w', 'Winche'), ('y', 'Soporte de vida')], default='nr', max_length=2),
        ),
    ]
