# Generated by Django 5.0.1 on 2025-04-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_rename_vessels_vessel_alter_equipocodecounter_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
