# Generated by Django 5.0.1 on 2025-02-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_equipo_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['control', 'frecuency', 'equipo__name']},
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
