# Generated by Django 5.0.1 on 2024-08-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_alter_equipo_volumen_alter_solicitud_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='nivel',
        ),
    ]
