# Generated by Django 5.0.1 on 2024-08-29 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_alter_equipo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.equipo'),
        ),
    ]
