# Generated by Django 5.0.1 on 2024-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_salida_adicional_solicitud_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionsuministro',
            name='fecha',
            field=models.DateField(),
        ),
    ]
