# Generated by Django 5.0.1 on 2024-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_salida_adicional_solicitud_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
