# Generated by Django 5.0.1 on 2025-03-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_remove_failurereport_evidence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['area', 'name'], 'permissions': (('access_all_assets', 'Access all assets'),)},
        ),
    ]
