# Generated by Django 5.0.1 on 2025-02-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_remove_failurereport_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
