# Generated by Django 5.0.1 on 2025-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_remove_failurereport_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bollard_pull',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
