# Generated by Django 5.0.1 on 2025-03-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_remove_failurereport_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='date_inv',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('b', 'BUEN ESTADO'), ('m', 'MAL ESTADO'), ('f', 'FUERA DE SERVICIO')], default='b', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='feature',
            field=models.TextField(verbose_name='Caracteristicas'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('a', 'Climatización'), ('b', 'Bomba'), ('c', 'Compresor'), ('d', 'Grúa'), ('e', 'Motor eléctrico'), ('f', 'Emergencias'), ('g', 'Generador'), ('h', 'Cilindro hidráulico'), ('i', 'Instrumentos y herramientas'), ('j', 'Distribución eléctrica'), ('k', 'Tanque de almacenamiento'), ('l', 'Gobierno'), ('m', 'Comunicación'), ('n', 'Navegación'), ('o', 'Maniobras'), ('p', 'Habitabilidad'), ('q', 'Informatica y vigilacia'), ('nr', 'No rotativo'), ('r', 'Motor a combustión'), ('t', 'Transmisión'), ('u', 'Unidad Hidráulica'), ('v', 'Valvula'), ('w', 'Winche'), ('x', 'Estructuras'), ('y', 'Soporte de vida'), ('z', 'Banco de baterias')], default='nr', max_length=2, verbose_name='Categoria'),
        ),
    ]
