# Generated by Django 5.0.1 on 2025-02-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_remove_failurereport_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequirement',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
        ),
    ]
