# Generated by Django 5.0.1 on 2025-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_userprofile_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='date_inv',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
