# Generated by Django 5.0.1 on 2024-08-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_alter_equipo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('a', 'Climatización'), ('b', 'Bomba'), ('c', 'Compresor'), ('e', 'Motor eléctrico'), ('g', 'Generador'), ('h', 'Cilindro hidraulico'), ('i', 'Instrumentos y herramientas'), ('k', 'Tanque de almacenamiento'), ('m', 'Comunicación'), ('n', 'Navegación'), ('nr', 'No rotativo'), ('r', 'Motor a combustión'), ('t', 'Transmisión'), ('v', 'Valvula'), ('w', 'Winche'), ('y', 'Soporte de vida'), ('z', 'Banco de baterias')], default='nr', max_length=2),
        ),
    ]
