# Generated by Django 5.0.1 on 2024-08-26 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_salida_suministro_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.salida'),
        ),
        migrations.AddField(
            model_name='salida',
            name='propietario',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
