# Generated by Django 5.0.1 on 2024-12-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_transaction_cant_report_transf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='clase',
        ),
        migrations.AddField(
            model_name='ruta',
            name='clase_date',
            field=models.DateField(blank=True, help_text='(Opcional) Fecha en que se renovó el certificado de clase, si es un dique de clase.', null=True),
        ),
    ]
