# Generated by Django 5.0.1 on 2024-08-27 03:18

import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_salida_suministro_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='sign_recibe',
            field=models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path),
        ),
    ]
