# Generated by Django 5.0.1 on 2024-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_activitylog_delete_location_asset_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='recibido_por',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='satisfaccion',
            field=models.BooleanField(default=False),
        ),
    ]
