# Generated by Django 5.0.1 on 2024-10-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_activitylog_delete_location_asset_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionsuministro',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
