# Generated by Django 5.0.1 on 2024-09-01 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_remove_equipo_imagen_alter_equipo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('com_estimado_motor', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumptions', to='got.equipo')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('equipo', 'fecha')},
            },
        ),
    ]
