# Generated by Django 5.0.1 on 2024-09-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_remove_equipo_imagen_alter_equipo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='lubricante',
        ),
        migrations.AddField(
            model_name='document',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_almacenamiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('a', 'Climatización'), ('b', 'Bomba'), ('c', 'Compresor'), ('d', 'Grúa'), ('e', 'Motor eléctrico'), ('g', 'Generador'), ('h', 'Cilindro hidráulico'), ('i', 'Instrumentos y herramientas'), ('k', 'Tanque de almacenamiento'), ('m', 'Comunicación'), ('n', 'Navegación'), ('nr', 'No rotativo'), ('r', 'Motor a combustión'), ('t', 'Transmisión'), ('u', 'Unidad Hidráulica'), ('v', 'Valvula'), ('w', 'Winche'), ('x', 'Estructuras'), ('y', 'Soporte de vida'), ('z', 'Banco de baterias')], default='nr', max_length=2),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
