# Generated by Django 5.0.1 on 2025-01-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_equipo_qr_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='qr_code_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
