# Generated by Django 5.0.1 on 2024-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_activitylog_delete_location_asset_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
