# Generated by Django 5.0.1 on 2024-10-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_transaction_cant_report_transf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='dpto',
            field=models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operaciones')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
