# Generated by Django 5.0.1 on 2024-10-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_activitylog_delete_location_asset_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccionsuministro',
            options={'permissions': (('can_add_supply', 'Puede añadir suministros'),)},
        ),
    ]
