# Generated by Django 5.0.1 on 2024-09-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_activitylog_delete_location_asset_modified_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='modified_by',
        ),
    ]
