# Generated by Django 5.0.1 on 2024-08-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_remove_ruta_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1 - Operadores'), (2, 'Nivel 2 - Operador Técnico'), (3, 'Nivel 3 - Proveedor especializado'), (4, 'Nivel 4 - Fabricante')], default=1),
        ),
    ]
