# Generated by Django 5.0.1 on 2024-08-19 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_alter_estator_megger_alter_excitatriz_megger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tasks',
        ),
        migrations.AddField(
            model_name='document',
            name='ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.ot'),
        ),
    ]
