# Generated by Django 5.0.1 on 2024-10-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_requirement_novedad_requirement_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
