# Generated by Django 5.0.1 on 2024-10-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_solicitud_dpto_alter_solicitud_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
