# Generated by Django 5.0.1 on 2024-12-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_solicitud_requested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excitatriz',
            name='pf_10min_l_tierra',
        ),
        migrations.RemoveField(
            model_name='excitatriz',
            name='pf_1min_l_tierra',
        ),
        migrations.RemoveField(
            model_name='excitatriz',
            name='pf_obs_l_tierra',
        ),
    ]
