# Generated by Django 5.0.1 on 2024-10-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_solicitud_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tipo',
            field=models.CharField(choices=[('i', 'Ingreso'), ('c', 'Consumo'), ('t', 'Transferencia'), ('e', 'Ingreso externo')], default='i', max_length=1),
        ),
    ]
