# Generated by Django 5.0.1 on 2024-08-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_remove_document_tasks_document_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='megger',
            name='date_report',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
