# Generated by Django 5.0.1 on 2024-10-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_alter_requirement_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'permissions': [('can_create_requirement', 'Can create requirement'), ('can_delete_requirement', 'Can delete requirement')]},
        ),
    ]
