# Generated by Django 5.0.1 on 2024-10-27 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_alter_transaction_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='megger',
            name='estator_pi_1min_l1_tierra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('justificacion', models.TextField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('a', 'Capitan'), ('b', 'Primer Oficial de puente'), ('c', 'Marino'), ('d', 'Jefe de maquinas'), ('e', 'Primer Oficial de maquinas'), ('f', 'Maquinista'), ('g', 'Otro')], max_length=1)),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='overtime',
            options={'permissions': [('can_approve_overtime', 'Puede aprobar horas extras')]},
        ),
    ]
