# Generated by Django 5.0.1 on 2024-12-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_remove_excitatriz_pf_10min_l_tierra_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='Megger'),
                migrations.DeleteModel(name='Estator'),
                migrations.DeleteModel(name='Excitatriz'),
                migrations.DeleteModel(name='RotorMain'),
                migrations.DeleteModel(name='RotorAux'),
                migrations.DeleteModel(name='RodamientosEscudos'),
            ]
        )
    ]
