# Generated by Django 5.0.1 on 2024-06-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0009_consumibles_control_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='date_inv',
            field=models.DateField(auto_now_add=True),
        ),
    ]
