# Generated by Django 5.0.1 on 2024-10-27 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0009_megger_estator_pi_1min_l1_tierra_overtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='nombre',
        ),
        migrations.AddField(
            model_name='overtime',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='overtime',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='got.asset'),
        ),
        migrations.AddField(
            model_name='overtime',
            name='cedula',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='overtime',
            name='nombre_completo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
