# Generated by Django 5.0.1 on 2024-11-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0010_remove_overtime_apellido_remove_overtime_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-creation_date'], 'permissions': (('can_approve', 'Aprobar solicitudes'), ('can_cancel', 'Puede cancelar'), ('can_view_all_rqs', 'Puede ver todas las solicitudes'))},
        ),
    ]
