# Generated by Django 5.0.1 on 2024-10-28 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0010_remove_overtime_apellido_remove_overtime_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'permissions': [('can_approve_overtime', 'Puede aprobar horas extras')]},
        ),
    ]
