# Generated by Django 5.0.1 on 2024-11-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0011_alter_solicitud_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-creation_date'], 'permissions': (('can_approve', 'Aprobar solicitudes'), ('can_cancel', 'Puede cancelar'), ('can_view_all_rqs', 'Puede ver todas las solicitudes'), ('can_transfer_solicitud', 'Puede transferir solicitudes'))},
        ),
    ]
