# Generated by Django 5.0.1 on 2024-11-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0013_remove_task_evidence_equipmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenthistory',
            name='date',
            field=models.DateField(),
        ),
    ]
