# Generated by Django 5.0.1 on 2024-08-06 03:41

import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0013_preoperacional_image_preoperacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darbaja',
            name='firma_autorizado',
            field=models.ImageField(upload_to=got.models.get_upload_path),
        ),
    ]
