# Generated by Django 5.0.1 on 2024-12-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0014_alter_image_salida_alter_suministro_salida_and_more'),
        ('preoperacionales', '0003_autorizado_preoperacional_authorized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salida',
            options={'managed': False, 'ordering': ['-fecha'], 'permissions': (('can_approve_it', 'Aprobar salidas'),)},
        ),
        migrations.AddField(
            model_name='image',
            name='preoperacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preoperacionales.preoperacional'),
        ),
        migrations.AddField(
            model_name='image',
            name='preoperacionaldiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preoperacionales.preoperacionaldiario'),
        ),
        migrations.AlterField(
            model_name='image',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.salida'),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suministros', to='got.salida'),
        ),
    ]
