# Generated by Django 5.0.1 on 2024-07-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0014_preoperacional_nombre_no_registrado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyhour',
            name='hour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
