# Generated by Django 5.0.1 on 2024-11-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0015_asset_show'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='Preoperacional'),
                migrations.DeleteModel(name='PreoperacionalDiario'),
            ],
        ),
    ]
