# Generated by Django 5.0.1 on 2024-12-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0015_alter_document_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='thumbnail',
        ),
    ]
