# Generated by Django 5.0.1 on 2024-11-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0015_asset_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='preoperacional',
        ),
        migrations.RemoveField(
            model_name='image',
            name='preoperacionaldiario',
        ),
    ]
