# Generated by Django 5.0.1 on 2024-11-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0015_move_overtime_to_overtime_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
