# Generated by Django 5.0.1 on 2024-11-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0015_move_overtime_to_overtime_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.equipo'),
        ),
    ]
