# Generated by Django 5.0.1 on 2024-12-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0015_alter_salida_options_image_preoperacional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministro',
            name='salida',
        ),
        migrations.AlterField(
            model_name='image',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='outbound.outbounddelivery'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='Salida'),
            ]
        ),
    ]
