# Generated by Django 5.0.1 on 2024-07-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0016_preoperacionaldiario_image_preoperacionaldiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failurereport',
            name='related_ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_report', to='got.ot'),
        ),
    ]
