# Generated by Django 5.0.1 on 2024-11-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0016_remove_image_preoperacional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
