# Generated by Django 5.0.1 on 2024-11-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0016_remove_image_preoperacional_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name='Preoperacional'),
                migrations.DeleteModel(name='PreoperacionalDiario'),
            ],
        ),
    ]
