# Generated by Django 5.0.1 on 2024-11-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0017_move_preoperacional_models'),
        ('preoperacionales', '0003_autorizado_preoperacional_authorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preoperacional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preoperacionales.preoperacional'),
        ),
        migrations.AddField(
            model_name='image',
            name='preoperacionaldiario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='preoperacionales.preoperacionaldiario'),
        ),
    ]
