# Generated by Django 5.0.1 on 2024-07-14 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0017_preoperacional_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preoperacional',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo'),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo'),
        ),
    ]
