# Generated by Django 5.0.1 on 2024-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0018_alter_preoperacional_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='combustible_level',
            field=models.CharField(choices=[('f', 'Lleno'), ('a', '3/4'), ('b', '1/2'), ('c', '1/4'), ('d', '1/8')], default='f', max_length=1),
        ),
    ]
