# Generated by Django 5.0.1 on 2024-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0018_image_preoperacional_image_preoperacionaldiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='area',
            field=models.CharField(choices=[('a', 'Motonave'), ('b', 'Buceo'), ('c', 'Barcazas'), ('o', 'Oceanografía'), ('l', 'Locativo'), ('v', 'Vehiculos'), ('x', 'Apoyo')], default='a', max_length=1),
        ),
    ]
