# Generated by Django 5.0.1 on 2024-07-20 17:36

import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0020_remove_preoperacionaldiario_conexiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='confirmado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='sign_supervision',
            field=models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path),
        ),
    ]
