# Generated by Django 5.0.1 on 2024-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0020_remove_preoperacionaldiario_conexiones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preoperacionaldiario',
            old_name='chaleto_reflectivo',
            new_name='chaleco_reflectivo',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='espejo_derecho',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='espejo_izquierdo',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='guardafango_derecho',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='guardafango_izquierdo',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='parales_derecho',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='parales_izquierdo',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='puerta_derecho',
        ),
        migrations.RemoveField(
            model_name='preoperacionaldiario',
            name='puerta_izquierdo',
        ),
        migrations.AddField(
            model_name='preoperacionaldiario',
            name='guardafango',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='preoperacionaldiario',
            name='parales',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AddField(
            model_name='preoperacionaldiario',
            name='placa_delantera',
            field=models.CharField(choices=[('a', 'Buena'), ('b', 'Descolorida'), ('c', 'Rota/Partida'), ('m', 'Mala')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='preoperacionaldiario',
            name='placa_trasera',
            field=models.CharField(choices=[('a', 'Buena'), ('b', 'Descolorida'), ('c', 'Rota/Partida'), ('m', 'Mala')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='preoperacionaldiario',
            name='puerta',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='bumper_delantero',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='bumper_trasero',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='capo',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='panoramico',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='persiana',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='stop',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='preoperacionaldiario',
            name='vidrio_panoramico_trasero',
            field=models.CharField(choices=[('l', 'Raya leve'), ('p', 'Rayón profundo'), ('f', 'Golpe fuerte'), ('b', 'Bueno')], default='b', max_length=1),
        ),
    ]
