# Generated by Django 5.0.1 on 2024-07-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0021_rename_chaleto_reflectivo_preoperacionaldiario_chaleco_reflectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperacional',
            name='agua',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preoperacional',
            name='condiciones',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preoperacional',
            name='control',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preoperacional',
            name='dormido',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preoperacional',
            name='enfermo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preoperacional',
            name='horas_trabajo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preoperacional',
            name='medicamentos',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
