# Generated by Django 5.0.1 on 2024-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0022_preoperacional_agua_preoperacional_condiciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='espacio_libre_cubierta',
        ),
        migrations.AlterField(
            model_name='ot',
            name='supervisor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='preoperacional',
            name='molestias',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='preoperacional',
            name='radio_aire',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='preoperacional',
            name='sueño',
            field=models.BooleanField(),
        ),
    ]
