# Generated by Django 5.0.1 on 2024-07-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0022_preoperacional_agua_preoperacional_condiciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preoperacional',
            name='dormido_anoche',
        ),
    ]
