# Generated by Django 5.0.1 on 2024-07-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0024_alter_solicitud_options_solicitud_cancel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preoperacional',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='preoperacionaldiario',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='failurereport',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.equipo'),
        ),
    ]
