version: '3.8'

services:
  postgres:
    image: postgres
    container_name: hivik-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - db-tier
    volumes:
      - hivik-postgres:/var/lib/postgresql/data
networks:
  db-tier:
    driver: bridge
volumes:
  data01: {}
  hivik-postgres:
