# megger_app/migrations/0001_initial.py
# Generated by Django 5.0.1 on 2024-XX-XX

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # si deseas asegurar orden, podrías hacer algo como:
        ('got', '0003_remove_task_ruta_delete_ruta'), 
        # para evitar problemas, pero si no, dejar vacío.
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Aquí NO hacemos nada en la BD (p. ej. no CreateModel)
                # porque las tablas 'got_megger', 'got_estator', etc. ya existen.
                # y definiremos managed=False en los modelos.
            ],
            state_operations=[
                # 1) Modelo Megger
                migrations.CreateModel(
                    name='Megger',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('date_report', models.DateField(auto_now_add=True, null=True, blank=True)),
                        ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.ot')),
                        ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
                    ],
                    options={
                        'db_table': 'got_megger',
                        'managed': False,
                    },
                ),

                # 2) Modelo Estator
                migrations.CreateModel(
                    name='Estator',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        (
                            'test_type',
                            models.CharField(
                                max_length=1,
                                choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')],
                                default='i'
                            )
                        ),
                        (
                            'time_type',
                            models.CharField(
                                max_length=1,
                                choices=[('1', '1 min'), ('2', '10 min')],
                                default='1'
                            )
                        ),
                        ('pi_1min_l1_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_1min_l2_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_1min_l3_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_1min_l1_l2', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_1min_l2_l3', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_1min_l3_l1', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),

                        ('pi_obs_l1_tierra', models.TextField(null=True, blank=True)),
                        ('pi_obs_l2_tierra', models.TextField(null=True, blank=True)),
                        ('pi_obs_l3_tierra', models.TextField(null=True, blank=True)),
                        ('pi_obs_l1_l2', models.TextField(null=True, blank=True)),
                        ('pi_obs_l2_l3', models.TextField(null=True, blank=True)),
                        ('pi_obs_l3_l1', models.TextField(null=True, blank=True)),

                        (
                            'megger',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='megger_app.megger'
                            )
                        ),
                    ],
                    options={
                        'db_table': 'got_estator',
                        'managed': False,
                    },
                ),

                # 3) Modelo Excitatriz
                migrations.CreateModel(
                    name='Excitatriz',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        (
                            'test_type',
                            models.CharField(
                                max_length=1,
                                choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')],
                                default='i'
                            )
                        ),
                        ('pi_1min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_10min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_obs_l_tierra', models.TextField(null=True, blank=True)),

                        (
                            'megger',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='megger_app.megger'
                            )
                        ),
                    ],
                    options={
                        'db_table': 'got_excitatriz',
                        'managed': False,
                    },
                ),

                # 4) Modelo RotorMain
                migrations.CreateModel(
                    name='RotorMain',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        (
                            'test_type',
                            models.CharField(
                                max_length=1,
                                choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')],
                                default='i'
                            )
                        ),
                        ('pi_1min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_10min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_obs_l_tierra', models.TextField(null=True, blank=True)),

                        # Estos pf_... existían, si ya los quitaste, no los declares.
                        # De ejemplo, uno pone ...
                        ('pf_1min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pf_10min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pf_obs_l_tierra', models.TextField(null=True, blank=True)),

                        (
                            'megger',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='megger_app.megger'
                            )
                        ),
                    ],
                    options={
                        'db_table': 'got_rotormain',
                        'managed': False,
                    },
                ),

                # 5) Modelo RotorAux
                migrations.CreateModel(
                    name='RotorAux',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        (
                            'test_type',
                            models.CharField(
                                max_length=1,
                                choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')],
                                default='i'
                            )
                        ),
                        ('pi_1min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_10min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pi_obs_l_tierra', models.TextField(null=True, blank=True)),

                        ('pf_1min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pf_10min_l_tierra', models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)),
                        ('pf_obs_l_tierra', models.TextField(null=True, blank=True)),

                        (
                            'megger',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='megger_app.megger'
                            )
                        ),
                    ],
                    options={
                        'db_table': 'got_rotoraux',
                        'managed': False,
                    },
                ),

                # 6) Modelo RodamientosEscudos
                migrations.CreateModel(
                    name='RodamientosEscudos',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        (
                            'test_type',
                            models.CharField(
                                max_length=1,
                                choices=[('i', 'Prueba Inicial'), ('f', 'Prueba Final')],
                                default='i'
                            )
                        ),
                        ('rodamientoas', models.TextField(null=True, blank=True)),
                        ('rodamientobs', models.TextField(null=True, blank=True)),
                        ('escudoas', models.TextField(null=True, blank=True)),
                        ('escudobs', models.TextField(null=True, blank=True)),
                        (
                            'megger',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='megger_app.megger'
                            )
                        ),
                    ],
                    options={
                        'db_table': 'got_rodamientosescudos',
                        'managed': False,
                    },
                ),
            ],
        ),
    ]
