# Generated by Django 5.0.1 on 2025-03-03 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('got', '0005_ot_closing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Valor monetario de adquisición (COP)', max_digits=18, null=True)),
                ('fp', models.DecimalField(blank=True, decimal_places=4, help_text='Factor de participación (entre 0 y 1)', max_digits=5, null=True)),
                ('asset', models.OneToOneField(limit_choices_to={'area__in': ['a', 'c']}, on_delete=django.db.models.deletion.CASCADE, related_name='cost_info', to='got.asset')),
            ],
        ),
    ]
