# Generated by Django 5.0.1 on 2025-03-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosAdministrativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.AddField(
            model_name='assetcost',
            name='costo_adicional',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de montos de financiaciones (COP)', max_digits=18),
        ),
        migrations.CreateModel(
            name='Financiacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del préstamo (COP)', max_digits=18)),
                ('plazo', models.PositiveIntegerField(help_text='Plazo en meses')),
                ('fecha_desembolso', models.DateField()),
                ('tasa_interes', models.DecimalField(decimal_places=4, help_text='Tasa de interés (ej. 0.05 para 5%)', max_digits=5)),
                ('no_deuda', models.CharField(help_text='Número de deuda', max_length=50)),
                ('periodicidad_pago', models.CharField(default='mensual', help_text='Periodicidad del pago de interés', max_length=20)),
                ('valor_financiacion', models.DecimalField(blank=True, decimal_places=2, help_text='Valor generado por la tasa de interés', max_digits=18, null=True)),
                ('supuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financiaciones', to='cont.supuesto')),
            ],
        ),
    ]
