# Generated by Django 5.0.1 on 2025-03-04 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0002_gastosadministrativos_assetcost_costo_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcost',
            name='valor_financiacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor de la financiación generado por la tasa de interés', max_digits=18),
        ),
    ]
