# Generated by Django 5.0.1 on 2025-03-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_remove_financiacion_supuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosadministrativos',
            name='mes',
            field=models.PositiveIntegerField(default=2, help_text='Mes (1-12)'),
            preserve_default=False,
        ),
    ]
