# Generated by Django 5.0.1 on 2025-03-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_remove_financiacion_supuesto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiacion',
            name='fecha_vencimiento',
        ),
    ]
