# Generated by Django 5.0.1 on 2025-03-06 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0003_remove_financiacion_supuesto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcost',
            options={'ordering': ['asset']},
        ),
        migrations.AddField(
            model_name='codigocontable',
            name='categoria',
            field=models.CharField(choices=[('ga', 'Gastos Administrativos'), ('cd', 'Costo Directo')], default='ga', help_text="Seleccione 'ga' para Gastos Administrativos o 'cd' para Costo Directo", max_length=2),
        ),
        migrations.CreateModel(
            name='CostoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código independiente para el costo directo', max_length=50, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción del costo directo', max_length=200)),
                ('total', models.DecimalField(decimal_places=2, help_text='Valor total del costo directo', max_digits=18)),
                ('mes', models.PositiveIntegerField(help_text='Mes (1-12)')),
                ('anio', models.PositiveIntegerField(help_text='Año')),
                ('assetcost', models.ForeignKey(help_text='Registro de AssetCost asociado', on_delete=django.db.models.deletion.CASCADE, related_name='costos_directos', to='cont.assetcost')),
            ],
        ),
    ]
