# Generated by Django 5.0.1 on 2025-03-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0004_gastosadministrativos_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código contable', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre o descripción asociada al código', max_length=200)),
            ],
        ),
    ]
