# Generated by Django 5.0.1 on 2025-03-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cont', '0004_remove_financiacion_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcost',
            name='cont_a_los_gastos',
        ),
    ]
