# Generated by Django 5.0.1 on 2025-03-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('got', '0002_ruta_task_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('proyecto', models.CharField(max_length=100)),
                ('requirements', models.TextField()),
                ('confirmado', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.asset')),
            ],
            options={
                'db_table': 'got_operation',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('novedad', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ope.operation')),
            ],
            options={
                'db_table': 'got_requirement',
                'permissions': [('can_create_requirement', 'Can create requirement'), ('can_delete_requirement', 'Can delete requirement')],
            },
        ),
    ]
