# Generated by Django 5.0.1 on 2025-03-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
