# Generated by Django 5.0.1 on 2024-11-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preoperacionales', '0001_move_preoperacional_models'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='preoperacional',
            table='got_preoperacional',
        ),
    ]
