# Generated by Django 5.0.1 on 2024-11-23 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preoperacionales', '0002_autorizado_alter_preoperacional_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='preoperacional',
            name='authorized',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='preoperacionales.autorizado'),
        ),
    ]
