# Generated by Django 5.0.1 on 2025-03-26 16:37

import dirtyfields.dirtyfields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_alter_equipo_date_inv_alter_equipo_estado_and_more'),
        ('preoperacionales', '0003_autorizado_preoperacional_authorized'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=6, unique=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('requested_by', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('OCCUPIED', 'Ocupado'), ('UNDER_MAINTENANCE', 'En Mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de Servicio'), ('REQUESTED', 'Solicitado'), ('NOT_AVAILABLE', 'No disponible')], default='AVAILABLE', max_length=20)),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='got.system')),
            ],
            options={
                'db_table': 'vehicle',
                'ordering': ['-brand'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
