# Generated by Django 5.0.1 on 2025-03-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preoperacionales', '0004_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('REQUESTED', 'Solicitado'), ('OCCUPIED', 'Ocupado'), ('UNDER_MAINTENANCE', 'En Mantenimiento'), ('OUT_OF_SERVICE', 'Fuera de Servicio'), ('NOT_AVAILABLE', 'No disponible')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleMovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida')], max_length=10)),
                ('requested_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_history', to='preoperacionales.vehicle')),
            ],
            options={
                'db_table': 'vehicle_movement_history',
                'ordering': ['-movement_time'],
            },
        ),
    ]
