# Generated by Django 5.0.1 on 2025-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preoperacionales', '0005_alter_vehicle_status_vehiclemovementhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemovementhistory',
            name='reason',
        ),
        migrations.AddField(
            model_name='vehiclemovementhistory',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemovementhistory',
            name='action',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('maintenance_in', 'Entrada a Mantenimiento'), ('maintenance_out', 'Salida de Mantenimiento'), ('service_in', 'Ingresó al Servicio'), ('service_out', 'Fuera de Servicio')], max_length=20),
        ),
    ]
