# Generated by Django 5.0.1 on 2025-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preoperacionales', '0006_remove_vehiclemovementhistory_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemovementhistory',
            name='action',
            field=models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('MAINTENANCE_IN', 'Entrada a Mantenimiento'), ('MAINTENANCE_OUT', 'Salida de Mantenimiento'), ('SERVICE_IN', 'Ingresó al Servicio'), ('SERVICE_OUT', 'Fuera de Servicio')], max_length=20),
        ),
    ]
