# Generated by Django 5.0.1 on 2025-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preoperacionales", "0007_alter_vehiclemovementhistory_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preoperacional",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
