# Generated by Django 5.0.1 on 2025-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preoperacionales', '0008_alter_preoperacional_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemovementhistory',
            name='action',
            field=models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('MAINTENANCE_IN', 'Entrada a Mantenimiento'), ('MAINTENANCE_OUT', 'Salida de Mantenimiento'), ('SERVICE_IN', 'Habilitado'), ('SERVICE_OUT', 'Fuera de Servicio')], max_length=20),
        ),
    ]
