# Generated by Django 5.0.1 on 2025-04-09 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preoperacionales", "0009_alter_vehiclemovementhistory_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preoperacionaldiario",
            name="kilometraje",
        ),
    ]
