# Generated by Django 5.0.1 on 2025-04-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preoperacionales", "0010_remove_preoperacionaldiario_kilometraje"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="preoperacional",
            name="authorized",
        ),
        migrations.RemoveField(
            model_name="preoperacional",
            name="autorizado",
        ),
        migrations.AddField(
            model_name="preoperacional",
            name="authorizer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="preoperacionales.authorizer",
            ),
        ),
        migrations.DeleteModel(
            name="Autorizado",
        ),
    ]
