# Generated by Django 5.0.1 on 2025-04-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "preoperacionales",
            "0011_authorizer_driver_remove_preoperacional_authorized_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="driver",
            table="preoperacionales_driver",
        ),
    ]
