# Generated by Django 5.0.1 on 2025-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preoperacionales", "0012_alter_driver_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="last_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
