# Generated by Django 5.0.1 on 2025-03-07 14:44

import django.db.models.deletion
import tic.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[tic.models.validate_title_word_count])),
                ('message', models.TextField()),
                ('ticket_type', models.CharField(choices=[('incidencia', 'Incidencia'), ('requerimiento', 'Requerimiento')], max_length=20)),
                ('category', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], max_length=20)),
                ('state', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('solution', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
