# Generated by Django 5.0.1 on 2025-02-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_count_date', models.DateField(help_text='Fecha de inicio de conteo para el plan. Inicialmente igual a base_intervention_date, pero se puede modificar manualmente')),
                ('period_start', models.DateField(help_text='Inicio del periodo de planificación')),
                ('period_end', models.DateField(help_text='Fin del periodo de planificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(help_text='Ruta asociada a este plan de mantenimiento', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='got.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(help_text='Mes (1-12)')),
                ('year', models.PositiveSmallIntegerField(help_text='Año')),
                ('planned_executions', models.PositiveIntegerField(default=0, help_text='Número de ejecuciones planificadas para este mes')),
                ('actual_executions', models.PositiveIntegerField(default=0, help_text='Número de ejecuciones reales registradas en este mes')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='mto.maintenanceplan')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('plan', 'month', 'year')},
            },
        ),
    ]
