# Generated by Django 5.0.1 on 2025-03-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntf', '0002_webpushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.URLField(max_length=500),
        ),
    ]
