# Generated by Django 5.0.1 on 2025-03-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntf', '0003_alter_webpushsubscription_endpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebPushSubscription',
        ),
    ]
