# Generated by Django 5.0.1 on 2025-01-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='excitatriz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='megger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rodamientosescudos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rotoraux',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rotormain',
            options={},
        ),
    ]
