# Generated by Django 5.0.1 on 2025-01-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meg', '0002_alter_estator_options_alter_excitatriz_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estator',
            old_name='pi_1min_l1_tierra',
            new_name='l1_tierra',
        ),
        migrations.AlterField(
            model_name='estator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='excitatriz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='megger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rodamientosescudos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rotoraux',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rotormain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
